[package]
name = "icn_blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
icn_common = { path = "../icn_common" }
serde = { workspace = true }
chrono = { workspace = true }
sha2 = "0.9"
ed25519-dalek = "1.0"
rand = "0.7"
log = { workspace = true }

[dev-dependencies]
tokio-test = "0.4"