[package]
name = "icn_blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
icn_currency = { path = "../icn_currency" }
icn_consensus = { path = "../icn_consensus" }
icn_core = { path = "../icn_core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
sha2 = "0.9"
uuid = { version = "0.8", features = ["v4"] }
ed25519-dalek = "1.0"