[workspace]
members = [
    "icn_core",
    "icn_blockchain",
    "icn_consensus",
    "icn_networking",
    "icn_identity",
    "icn_governance",
    "icn_smart_contracts",
    "icn_virtual_machine",
    "icn_api",
    "icn_storage",
    "icn_shared"
]
default-run = "icn_core"

resolver = "2"