[server]
host = "127.0.0.1"
port = 8080
debug = true
cert_file_path = "/opt/InterCooperative-Network-Node/cert.pem"
key_file_path = "/opt/InterCooperative-Network-Node/key.pem"
cert_password = ""  # Leave empty if there is no password

[database]
urls = ["postgresql://user:password@localhost/db1", "postgresql://user:password@localhost/db2"]
