[package]
name = "icn_smart_contract"
version = "0.1.0"
edition = "2021"

[dependencies]
icn_core = { path = "../icn_core" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
log = "0.4"
thiserror = "1.0"

[dev-dependencies]
tokio-test = "0.4"