# icn_consensus/Cargo.toml

[package]
name = "icn_consensus"
version = "0.1.0"
edition = "2021"

[dependencies]
icn_blockchain = { path = "../icn_blockchain" }
icn_shared = { path = "../icn_shared" }  # Ensure this line is present
