[package]
name = "icn_consensus"
version = "0.1.0"
edition = "2021"

[dependencies]
icn_core = { path = "../icn_core" }
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
thiserror = "1.0"
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
tokio-test = "0.4"