[package]
name = "icn_common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1.0"
sha2 = "0.9"
ed25519-dalek = "1.0"
log = "0.4"

[dev-dependencies]
rand = "0.8"
tokio = { version = "1.0", features = ["full"] }
tokio-test = "0.4"
