[package]
name = "icn_language"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.0"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
log = "0.4"
icn_common = { path = "../icn_common" }
icn_vm = { path = "../icn_vm" }

[dev-dependencies]
env_logger = "0.10"