[package]
name = "icn_zkp"
version = "0.1.0"
edition = "2021"

[dependencies]
bellman = "0.11.0" # Trying an earlier version to avoid conflicts
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
ed25519-dalek = "1.0"
rand = "0.8"
icn_common = { path = "../icn_common" }
