[package]
name = "icn_zkp"
version = "0.1.0"
edition = "2021"

[dependencies]
bellman = "0.11.1"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
ed25519-dalek = "1.0"
rand = "0.8"
bitvec = { path = "../../vendor/bitvec" }
funty = { path = "../../vendor/funty" }
