[package]
name = "icn_zkp"
version = "0.1.0"
edition = "2021"

[dependencies]
icn_common = { path = "../icn_common" }
bellman = "0.11.0"
bls12_381 = "0.6.0"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"

[dev-dependencies]
criterion = "0.3"