[package]
name = "icn_storage"
version = "0.1.0"
edition = "2021"

[dependencies]
icn_common = { path = "../icn_common" }
# Add other dependencies as needed

[dev-dependencies]
# Add dev dependencies as needed
