[package]
name = "icn_smart_contracts"
version = "0.1.0"
edition = "2021"

[dependencies]
icn_common = { path = "../icn_common" }
icn_vm = { path = "../icn_vm" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
log = "0.4"
pest = "2.1"
pest_derive = "2.1"